### ISSUE TITLE
Missing Parallax Continued Dependencies Unity.Burst, Unity.Mathematics and Unity.Collections 

### ISSUE THREAD

**Issue by RagnarTheRagnar** [Gameslinx/Parallax-Continued#2]
Was trying to get a OPM, Infinite Discovery mod pack working. Spent a lot of time trying to get Parallax 2.0.8 to work, saw that the Parallax continued had support for OPM. Removed the OPX mods for OPM. Removed all the OPM Parallax stuff and reinstalled Korpuricous, OPM and Parallax Continued && the OPM Continued Configs manually and getting this error: 

`[LOG 17:54:45.109] [Parallax] Starting Harmony patching...
[ERR 17:54:45.110] ADDON BINDER: Cannot resolve assembly: Unity.Burst, Culture=neutral, PublicKeyToken=null

[ERR 17:54:45.111] ADDON BINDER: Cannot resolve assembly: Unity.Burst, Culture=neutral, PublicKeyToken=null

[EXC 17:54:45.115] [ModuleManager] Exception while calling Parallax.ConfigLoader.ModuleManagerPostLoad(): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Unity.Burst, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.`

Attached relevant log files for review. More then happy to remove any suspect mods if needed for testing.

[KSP.log](https://github.com/user-attachments/files/17004192/KSP.log)
[ModuleManager.log](https://github.com/user-attachments/files/17004193/ModuleManager.log)
[Kopernicus.log](https://github.com/user-attachments/files/17004194/Kopernicus.log)

**Comment by Gameslinx** [comment]
Your log indicates that you're missing KSPBurst, which Parallax Continued depends on. You can get it here: https://github.com/KSPModdingLibs/KSPBurst/releases

Let me know if installing KSPBurst fixes those exceptions

**Comment by RagnarTheRagnar** [comment]
Installed KSPBurst. No errors now on launch and Korpuricous has finally loaded without an error in the main menu Wowza! Ty.

Ill go back to testing OPX and Infinite discoveries to see if anything else is causing issues. But nice to have this baseline finally.

Thanks for the fast response I must've missed the dependency somewhere...
