### ISSUE TITLE
Rehoming KSC breaks Parallax Continued

### ISSUE THREAD

**Issue by lOmicronl** [Gameslinx/Parallax-Continued#3]
I am trying Parallax Continued for the first time, and very much enjoying the upgraded visuals :) However, there is a problem.

I'm using the Kcalbeloh System mod, and have downloaded and installed the support patch for Parallax Continued. Out of the box, everything works. But when I go into the Kcalbeloh settings file, and activate the rehoming function, KSP fails to start. The rehoming function is meant to move the KSC to a planet in the Kcalbeloh system, so the player can start their playthrough there.

Without Parallax Continued, but with a whole big pile of other mods, this worked fine.

On the other hand, even in a minimal install with just Kcalbeloh and Parallax Continued and their respective dependencies, the problem can be reproduced at will. During startup, after everything is loaded and right before the main menu appears, KSP hangs on the loading screen with the loading indicator in the bottom right corner free-spinning. Even waiting 15 minutes at this stage does not let the game load.

The full log from the minimum setup is here: https://www.dropbox.com/scl/fi/appnbglpzlky6g806bgo0/KSP.log?rlkey=3cmdtypcbhhrecdehmtyipjvk&dl=0

The exception thrown is:

[EXC 17:08:18.670] ArgumentException: An item with the same key has already been added. Key: Kerbin Zn0000 (PQ)
	System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <9577ac7a62ef43179789031239ba8798>:0)
	System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <9577ac7a62ef43179789031239ba8798>:0)
	Parallax.PQSMod_Parallax.OnQuadBuilt (PQ quad) (at <70834aa898df44b2bfc249c5987b594c>:0)
	PQS.Mod_OnQuadBuilt (PQ quad) (at <4b449f2841f84227adfaad3149c8fdba>:0)
	PQS.BuildQuad (PQ quad) (at <4b449f2841f84227adfaad3149c8fdba>:0)
	PQ.Build () (at <4b449f2841f84227adfaad3149c8fdba>:0)
	Parallax.Harmony_Patches.QuadSetVisiblePatch.Prefix (PQ __instance) (at <70834aa898df44b2bfc249c5987b594c>:0)
	(wrapper dynamic-method) PQ.PQ.SetVisible_Patch1(PQ)
	PQ.UpdateVisibility () (at <4b449f2841f84227adfaad3149c8fdba>:0)
	PQ.UpdateSubdivision () (at <4b449f2841f84227adfaad3149c8fdba>:0)
	PQ.UpdateSubdivision () (at <4b449f2841f84227adfaad3149c8fdba>:0)
	PQ.UpdateSubdivision () (at <4b449f2841f84227adfaad3149c8fdba>:0)
	PQ.UpdateSubdivision () (at <4b449f2841f84227adfaad3149c8fdba>:0)
	PQ.UpdateSubdivision () (at <4b449f2841f84227adfaad3149c8fdba>:0)
	(wrapper dynamic-method) PQS.PQS.UpdateQuadsInit_Patch1(PQS)
	(wrapper dynamic-method) PQS.PQS.StartSphere_Patch0(PQS,bool)
	PQS.ForceStart () (at <4b449f2841f84227adfaad3149c8fdba>:0)
	PSystemSetup.ForceInitPQS (PQS pqsIn, UnityEngine.Transform target) (at <4b449f2841f84227adfaad3149c8fdba>:0)
	PSystemSetup+<SetupLaunchSites>d__38.MoveNext () (at <4b449f2841f84227adfaad3149c8fdba>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <12e76cd50cc64cf19e759e981cb725af>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

Please advise if:
   - Parallax Continued is just not compatible with rehoming KSC, or
   - it should work, but Prallax Continued requires a bugfix, or
   - it should work, but Kcalbeloh requires a bugfix.

**Comment by Gameslinx** [comment]
I'm going to mark this as stale for now as it seems low priority at the moment. It's on the todo list, but this may be an issue Kcalbeloh instead. Thanks for the report
