### ISSUE TITLE
Compiling guide from the forum post

### ISSUE THREAD

**Issue by JacobB094** [Gameslinx/Parallax-Continued#4]
With the forums down and no timeline for them being back up, your excellent post on setting up an environment for compiling KSP plugins is gone. Sadly, Wayback Machine didn't archive it. Could you reproduce it on Github? 

I have compiled from source before, but it seems that I missed a step when reinstalling everything.

**Comment by Gameslinx** [comment]
I'll update the wiki in the coming days with a proper guide, thanks for the headsup. Was expecting the forums to be back up by now...

**Comment by JacobB094** [comment]
So did I, but apparently, it's now up to someone at T2 to apply a supposedly simple configuration fix. Which, I imagine, is not exactly a top priority of theirs, so to speak.

**Comment by Gameslinx** [comment]
This should do the trick, let me know if you run into any issues and I'll edit the post:
https://github.com/Gameslinx/Parallax-Continued/wiki/Compiling-From-Source

**Comment by dandoesgithub** [comment]
Wanted to say that the forums are back now
