### ISSUE TITLE
Infinite Black Loading Screen post install

### ISSUE THREAD

**Issue by RealRobertBrownieJr** [Gameslinx/Parallax-Continued#5]
game worked great before,  decided to install parallax continued, installed the regular parallax first then the continued stuff 
game initially loads with loading bar & logogs etc  then the game hits another second load screen which is all black and has the planets rotating in the corner where it stays forever and doesn't actually load. 

ksp log: https://drive.google.com/file/d/1T-R7PP0S9Ts9wrf9qI79y4eFvROT1qDP/view?usp=sharing 

tried reinstalling a few times now changing folders been trying to fix it with no joy

**Comment by RealRobertBrownieJr** [comment]
I did pick a couple of errors out another guide saud they can help a lot 

[ERR 16:25:06.922] ADDON BINDER: Cannot resolve assembly: EVEManager, Culture=neutral, PublicKeyToken=null

[ERR 16:25:06.922] ADDON BINDER: Cannot resolve assembly: EVEManager, Culture=neutral, PublicKeyToken=null

[ERR 16:25:06.924] ADDON BINDER: Cannot resolve assembly: Utils, Culture=neutral, PublicKeyToken=null

[ERR 16:25:06.924] ADDON BINDER: Cannot resolve assembly: Utils, Culture=neutral, PublicKeyToken=null

**Comment by Gameslinx** [comment]
Hiya, I'm not at my PC at the moment to take a proper look until later today

You don't need to install regular Parallax for Parallax Continued to work

There are install instructions on the Patreon post and in the download - please make sure you follow these perfectly!

If you're still having issues I'll be back to take a proper look in a few hours

**Comment by RealRobertBrownieJr** [comment]
deleting the old setting cfg did it bt he looks of it :) 
first time I removed old parallax then copied the new folder in and got an error about missing files but i deleted everything re copied the files, deleted the cfg and it seems to be working

**Comment by RealRobertBrownieJr** [comment]
now i click options to change the graphics settings and it happens there  so its installed at least by the looks of it

**Comment by Gameslinx** [comment]
Is everything working now? Parallax won't cause a crash from main menu -> graphics settings
