### ISSUE TITLE
Choosing Rescale Seed

### ISSUE THREAD

**Issue by svm420** [Gameslinx/Parallax-Continued#7]
Hi I recently compiled the mod from source to try it out and I am playing with a 3.2x rescale. I saw the different cfg file you distribute for 2.5, 3.5 and 5.4 rescale and that you change the seed in that file to stop the space center from having trees all over it. I tried the seeds from those file for the rescale I am using but still am having trees overgrow the space center lol. I am creating this issue to ask if there is a way to adjust the seed without having to restart the game. If not would that be something that could be added to simplify finding a good seed? Thank you for the mod, your time and allowing it to be compiled independently.

**Comment by Gameslinx** [comment]
Hit Ctrl+P when in flight to open the editor - you'll first need to disable colliders in the config file (GameData/Parallax/Config/ParallaxGlobalConfig.cfg) by setting collisionLevel to -1.

The noise seed can be edited via the Ctrl+P GUI - find the OakTree scatter (not OakTreeTop) and change the seed. Note, I'm referring to the 'Noise' seed, not the 'Distribution' seed - there are two seed values - one for the placement of each individual tree on its terrain triangle, and one for the overall distribution. I'm sure you'll find it :)
