### ISSUE TITLE
Game Crash On Linux

### ISSUE THREAD

**Issue by tetonis** [Gameslinx/Parallax-Continued#8]
[KSP.log](https://github.com/user-attachments/files/17667598/KSP.log)
It seems Parallax is constantly throwing index out of range errors leading up to the crash. This happens immediately after entering flight mode and makes the game unplayable on the Linux version.

**Comment by connorcpu** [comment]
i'm having the exact same issue but my KSPBurst seems to be working fine and it doesn't crash on load it crashes a during flight (and tries to produce a coredump file in /var of several dozen GB) 

[KSP.log](https://github.com/user-attachments/files/18462090/KSP.log)

**Comment by connorcpu** [comment]
google told me in this situation i should do @Gameslinx ,let's see if that's considered rude or not
