### ISSUE TITLE
Game stuck on loading screen when trying to access either any save, create a save or going into 

### ISSUE THREAD

**Issue by Mortadelyfile** [Gameslinx/Parallax-Continued#9]
The game becomes stuck on loading screen when trying to access either any save, create a save or going into settings.
Happens on a brand new game which only has installed Parallax-Continued. Also errors star showing on screen of Kopernicus and Parallax.

**Comment by Gameslinx** [comment]
Attach your KSP.log file please

**Comment by Gameslinx** [comment]
Load up the game to where it gets stuck (when the planets spin smoothly), close the game and send the log - it should be small enough at that point. If not, package it up as a .zip and send that instead.

**Comment by Gameslinx** [comment]
Closing due to lack of info

**Comment by Mortadelyfile** [comment]
[KSP.log](https://github.com/user-attachments/files/17805101/KSP.log)
Hey, sorry for the wait and maybe this is too late but my PC was playing Brick until now.
There's the KSP.log, up to the point where planets spin smoothly after trying to enter settings.
Only mods are Parallax Continued and Blackrack's Clouds.

**Comment by Gameslinx** [comment]
It looks like you've installed Parallax Continued over the top of the old Parallax. Parallax Continued is a replacement, and doesnt' rely on old parallax (it will break with it)
Can you delete the various Parallax folders in your GameData and install the ones from the Parallax Continued zip you downloaded?

**Comment by Mortadelyfile** [comment]
Ok, that seem to do it, tried openin gmae few times and all worked, even new safe, kinda amazed that in all the copies and different instances I made in all I left some old Parallax files (In some I didn't even install Parallax, probably file contamination on my part).
Anyway, thank you very much.
